version: '3.7'
services:
    db:
        image: postgres:12-alpine
        container_name: tripbot_discord_db
        restart: always
        env_file: .env
        ports:
            - 5432:5432/tcp
        volumes:
            - tripbot_discord_db_data:/var/lib/postgresql/data
volumes:
    tripbot_discord_db_data:
        name: tripbot_discord_data
        driver: local
